### ISSUE TITLE
Certified Copies :  Multiple Fields Showing Incorrect Values

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#7937]
**Bug Description:**
Multiple fields in birth, death and marriage declaration show wrong values in the certificates.

**Steps to reproduce:**

1. Login as RA/local reg/ national reg.
2. Navigate to ready to print workqueue.
3. Download any record and click on 'Print'.
4. Select any template for certificate printing.
5. Compare the values from 'view' page with the certificate.

**Actural Result:**
Following fields show incorrect values - 
1. For birth: 

- [x] - incorrect BRN
- [x] - Shows nationality in short form, for ex: BD is shown for Bangladesh, FA is shown for Farajaland.
- [x] - When age is given instead of DOB, it shows 01.01. [calculated year from age]
- [x] - Always shows 'doctor' for occupation no matter what the input was.
- [x] - Wrong full name for informant : Shows the short form of nationality in place of last name.
- [x] - Wrong place of certification

2. For death:

- [x] - incorrect DRN
- [x] - When age is given instead of DOB, it shows 01.01. [calculated year from age]
- [x] - Shows nationality in short form, or ex: BD is shown for Bangladesh, FA is shown for Farajaland.
- [ ] - Incorrect informant's relationship to deceased.
- [x] - Incorrect date of certification.
- [x] - incorrect place of certification.

3. For marriage:

- [x] - When age is given instead of DOB, it shows 01.01. [calculated year from age]
- [x] - Shows nationality in short form, for ex: BD is shown for Bangladesh, FA is shown for Farajaland.
- [x] - Incorrect relationship to spouses for witness 1 and witness 2. [ shows 'Head of Groom's Family' for witness 1; 'Head of Bride's family' for witness 2' ]

4. For all events, address fields are not working properly.

- [x] - when 'health institution' is selected as a place of birth/place of death, in certificates, district name is shown beside the hospital name, on the same line.
- [x] - If residential address/ other -> any country except Farajaland is chosen for any address field, then address is not shown on certificate.

**Expected Result:**
All fields should show correct values.

**Screenshots:**

1. For birth:

![Image](https://github.com/user-attachments/assets/f2826c3e-935f-43f7-978a-77eff3568300)

2. For death:

![Image](https://github.com/user-attachments/assets/3cbc3664-4e1a-4b01-8b3d-70b907b8564e)

3. For marriage:

![Image](https://github.com/user-attachments/assets/a3cfa639-1daf-41ae-937e-56da1b6d27aa)

4. For all events, address fields are not working properly.

- [x] - when 'health institution' is selected as a place of birth/place of death, in certificates, district name is shown beside the hospital name, on the same line.

![Image](https://github.com/user-attachments/assets/0647b15b-649d-4993-a6a9-54c97f2bfb7e)

- [x] - If residential address/ other -> any country except Farajaland is chosen for any address field, then address is not shown on certificate.

![Image](https://github.com/user-attachments/assets/f5dcbd68-c9f5-4b11-9b36-887d5b2fdd10)

**Tested on:**
https://ocrvs-7584.opencrvs.dev/

**Comment by tareq89** [comment]
@tiri39 , new ticket needs to be opened.
1. If informant information is corrected, it isn't reflected on the declaration after approval.
2. In marriage declarations, witness 1 and 2 relation to the marriage (ex: head of the family etc) isn't reflected in the declaration data.

**Comment by tiri39** [comment]
Fixed.

1. Birth : 
    - When informant is not father / mother and father's / mother's details are not given -> shown ", ," for 'Resident at' field in both father's and mother's section.

![Image](https://github.com/user-attachments/assets/9aebd345-0b06-462d-ac71-7b943630c9af)

2. Death :  
    - 'Place of birth' should be removed as we don't take any input for this in death declaration form.
    - 'Date of death' is showing incorrect value ( the value of 'date of birth' / 'age' )
    
![Image](https://github.com/user-attachments/assets/ddb19c47-bdf9-4a28-a159-81620ce3b538)

3. Marriage : 
    - If Groom's DOB and Bride's AGE is given, in the certificates, Groom's DOB and Bride's DOB (converted from given Age) are shown.
    
![Image](https://github.com/user-attachments/assets/9f5d13ef-ba13-4501-a108-316e92c7e074)
     - If Groom's AGE and Bride's DOB is given, in the certiicates, Groom's AGE and Bride's AGE ( converted from DOB , but not showing any value, only showing ' years old' )
    

![Image](https://github.com/user-attachments/assets/2465ad2a-3a5f-486f-bedf-fda0194c8771)

**Comment by tareq89** [comment]
from now on, it will always show date instead of years

**Comment by tiri39** [comment]
Not Fixed.

Foe Birth and Death : 
- Showing "[district], [province], [province]" instead of "[district], [province], [country]" for the field 'Resident at' / 'Usual place of residence' when country is selected 'Farajaland'. 

![Image](https://github.com/user-attachments/assets/821827c6-b154-4be4-820f-6498d6aaff06)

- Showing 'undefined' for the field 'Resident at' / 'Usual place of residence' when any country is selected other than 'Farajaland'.

![Image](https://github.com/user-attachments/assets/55f2f8e0-d3e2-432e-a595-a6dd8c147417)


For Marriage : 

- Showing '  years old' for Bride's DOB when, Groom's AGE and Bride's DOB is given.

![Image](https://github.com/user-attachments/assets/e9f6ea2e-a475-4354-864a-bed9e2cb2ff2)

**Comment by tiri39** [comment]
Not Fixed yet :

For birth - When informant is not father / mother and father's / mother's details are not given -> shown ", ," for 'Resident at' field in both father's and mother's section.

![Image](https://github.com/user-attachments/assets/328fe16a-0b3a-4ec1-885f-008853dc643b)

**Comment by tiri39** [comment]
Fixed.

![Image](https://github.com/user-attachments/assets/481591bd-9a32-4c2c-8391-76aea6ac1d3d)
